#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

alias gofiches="cd $HOME/Library/Mobile\ Documents/iCloud~md~obsidian/Documents"
alias start_ml="start_conda && conda activate machine_learning"
alias gvim="nvim --listen 127.0.0.1:55432 ."
alias docker-compose="docker compose"

alias jcode='run_vscode_profile --profile=java '
alias mcode='run_vscode_profile --profile=misc '
alias pcode='run_vscode_profile --profile=python '
alias ccode='run_vscode_profile --profile=c '
alias cscode='run_vscode_profile --profile=csharp '
alias comcode='build_vscode_settings && code --user-data-dir="$HOME/.config/vscode-profiles/common/data" --extensions-dir="$HOME/.config/vscode-profiles/common/extensions"'
alias wcode='run_vscode_profile --profile=web '

alias yfire="screen -dmS firefox-youtube /Applications/Firefox.app/Contents/MacOS/firefox-bin -p youtube --no-remote"
alias afire="screen -dmS firefox-ai /Applications/Firefox.app/Contents/MacOS/firefox-bin -p ai --no-remote 'https://chat.openai.com/chat'"
alias dfire="screen -dmS firefox-dev /Applications/Firefox.app/Contents/MacOS/firefox-bin -p dev --no-remote 'https://github.com'"
alias fire="screen -dmS firefox /Applications/Firefox.app/Contents/MacOS/firefox-bin -p default --no-remote"

alias tmux="tmux -f $HOME/.config/tmux/tmux.conf"
alias tmux-sessionizer="$HOME/.config/tmux/tmux-sessionizer.sh"
alias tms="tmux-sessionizer"
alias google-chrome="/Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome"
# alias tmux-cht="$HOME/.config/tmux/tmux-cht.sh"
alias cht="$HOME/.config/tmux/tmux-w3.sh"
# alias cht="$HOME/.config/tmux/tmux-cht.sh"


# alias chrome="screen -dmS google-chrome /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory='Default' --new-window"
# alias achrome="screen -dmS google-chrome-ai /Applications/Google\ Chrome.app/Contents/MacOS/Google\ Chrome --profile-directory='Profile 1' --new-window 'https://chat.openai.com/chat'"

alias python='python3'
alias pip='pip3'

# ssh
# alias login_ssh="ssh $SSH_USER@$SSH_HOST"

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# git
alias gitgraph="git log --oneline --graph --decorate --all"
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"
alias kubedev="kubectl -n dev"


case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	;;

Linux)
	# echo 'Linux'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
