  - name: "Ensure Git Repository Present"
    git:
      repo: {{ repository }}
      dest: "{{ home }}/.config"
      recursive: false

  - name: Check .zshrc exists
    stat:
      path: "{{ home }}/.zshrc"
    register: stat_result

  - name: Ensure zsh sourced
    shell: |
        touch {{ home }}/.zshrc
        echo "source {{ home }}/.config/zsh/.zshrc" >> "{{ home }}/.zshrc"
        source {{ home }}/.zshrc
    changed_when: false
    when: not stat_result.stat.exists

  - name: Add Hombrew Taps
    community.general.homebrew_tap:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ homebrew_taps }}"

  - name: Ensure Homebrew Packages Installed
    community.general.homebrew:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ homebrew_installed_packages }}"

  - name: Ensure Homebrew Casks Installed
    community.general.homebrew_cask:
      name: "{{ item.name | default(item) }}"
      state: "{{ item.state | default('present') }}"
    loop: "{{ homebrew_cask_apps }}"

  - name: "Use OTC"
    command: "otc.sh use"

  - name: "Ensure Git Repository Updated"
    git:
      repo: {{ repository }}
      dest: "{{ home }}/.config"

  - name: "Delete OTC"
    command: "otc.sh delete"
