#!/usr/bin/env sh
yabai -m space 1 --label one
yabai -m space 2 --label two
yabai -m space 3 --label three
yabai -m space 4 --label four
yabai -m space 5 --label five
yabai -m space 6 --label six
yabai -m space 9 --label nine

# float system preferences. Most of these just disable Yabai form resizing them.
yabai -m rule --add app="^System Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Finder$" sticky=on layer=above manage=off
yabai -m rule --add app="^Alfred Preferences$" sticky=on layer=above manage=off
yabai -m rule --add app="^Disk Utility$" sticky=on layer=above manage=off
yabai -m rule --add app="^System Information$" sticky=on layer=above manage=off
yabai -m rule --add app="^Activity Monitor$" sticky=on layer=above manage=off
yabai -m rule --add app="^Path Finder$" manage=off
yabai -m rule --add app="^Logi Options$" manage=off
yabai -m rule --add title="MovieWriter" manage=off sticky=on layer=above manage=off
# yabai -m rule --add app="MovieWriter.*" sticky=on layer=above manage=off

yabai -m rule --add app="Main" manage=off
yabai -m rule --add app="Field" manage=off
yabai -m rule --add app="java" manage=off


yabai -m config window_placement second_child
yabai -m config window_topmost off
yabai -m config window_opacity off
yabai -m config window_opacity_duration 0.00
yabai -m config active_window_opacity 1.0
yabai -m config window_border off
yabai -m config auto_balance off
yabai -m config split_ratio 0.50
yabai -m config mouse_modifier ctrl
yabai -m config mouse_action2 resize
yabai -m config mouse_action1 move
yabai -m config layout bsp
yabai -m config top_padding 0
yabai -m config bottom_padding 0
yabai -m config left_padding 0
yabai -m config right_padding 0
yabai -m config window_gap 0

#Limelight addon (Kill it and start it each time Yabai starts)
killall limelight &>/dev/null
limelight --config ~/.config/limelight/limelightrc &>/dev/null &

echo "yabai configuration loaded.."

