- hosts: "current"
  become: true

  tasks:
    - name: MacOS
      var_files: 
        - ./vars/commons.yml
        - ./vars/darwin.yml
      include_tasks: ./tasks/darwin.yml
      when: ansible_facts['os_family'] == "Darwin"

    - name: Ubuntu
      var_files: 
        - ./vars/commons.yml
        - ./vars/ubuntu.yml
      include_tasks: ./tasks/ubuntu.yml
      when: ansible_facts['distribution'] == "Ubuntu"
