#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export HISTIGNORE='*sudo -S*'

export PATH="$HOME/.local/bin":$PATH

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# dotnet
export PATH="$PATH:$HOME/.dotnet/tools"

# racket
# export PATH="$PATH:/Applications/Racket/bin"

# FZF
export FZF_DEFAULT_OPTS='--bind=shift-tab:up,tab:down' 
