#!/bin/sh
HISTSIZE=1000000
SAVEHIST=1000000

export HISTIGNORE='*sudo -S*'

export PATH="$HOME/.local/bin":$PATH
export PATH="$HOME/.config/bin":$PATH

# pnpm
export PNPM_HOME="$HOME/Library/pnpm"
export PATH="$PNPM_HOME:$PATH"
# pnpm end

# dotnet
export PATH="$PATH:$HOME/.dotnet/tools"

# racket
# export PATH="$PATH:/Applications/Racket/bin"

# FZF
export FZF_DEFAULT_OPTS='--bind=shift-tab:up,tab:down' 


# AndroidStudio
PATH=$PATH:$HOME/Library/Android/sdk/emulator
PATH=$PATH:$HOME/Library/Android/sdk/tools
PATH=$PATH:$HOME/Library/Android/sdk/tools/bin
PATH=$PATH:$HOME/Library/Android/sdk/platform-tools
export ANDROID_HOME=$HOME/Library/Android/
# export JAVA_HOME=`/usr/libexec/java_home -v 1.8`
export JAVA_HOME=`/usr/libexec/java_home -v 11`
# on-corretto-11.jdk
