#!/bin/sh
alias zsh-update-plugins="find "$ZDOTDIR/plugins" -type d -exec test -e '{}/.git' ';' -print0 | xargs -I {} -0 git -C {} pull -q"
alias nvimrc='nvim ~/.config/nvim/'

alias gofiches="cd $HOME/Library/Mobile\ Documents/iCloud~md~obsidian/Documents"
alias start_ml="start_conda && conda activate machine_learning"
alias gvim="lvim"

alias jcode='run_vscode_profile --profile=java '
alias mcode='run_vscode_profile --profile=misc '
alias pcode='run_vscode_profile --profile=python '
alias ccode='run_vscode_profile --profile=c '
alias comcode='build_vscode_settings && code --user-data-dir="$HOME/.config/vscode-profiles/common/data" --extensions-dir="$HOME/.config/vscode-profiles/common/extensions"'
alias wcode='run_vscode_profile --profile=web '


alias python='python3'
alias pip='pip3'

# ssh
# alias login_ssh="ssh $SSH_USER@$SSH_HOST"

# confirm before overwriting something
alias cp="cp -i"
alias mv='mv -i'
alias rm='rm -i'

# git
alias gitgraph="git log --oneline --graph --decorate --all"
alias gitlog="git log --graph --pretty=format:'%Cred%h%Creset -%C(yellow)%d%Creset %s %Cgreen(%cr) %C(bold blue)<%an>%Creset' --abbrev-commit"


case "$(uname -s)" in

Darwin)
	# echo 'Mac OS X'
	;;

Linux)
	# echo 'Linux'
	;;

CYGWIN* | MINGW32* | MSYS* | MINGW*)
	# echo 'MS Windows'
	;;
*)
	# echo 'Other OS'
	;;
esac
